=== OSMLatam/OSM-Notes-Ingestion/json-schema/osm-jsonschema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/OSMLatam/OSM-Notes-profile/blob/main/json-schema/osm-jsonschema.json",
  "title": "JSON schema for OSM json files from Overpass",
  "description": "This is the JSON schema for the files retrieved from an Overpass query",
  "type": "object",
  "properties": {
    "version": {
      "description": "OpenStreetMap API version",
      "type": "number",
      "exclusiveMinimum": 0
    },
    "generator": {
      "description": "Overpass version",
      "type": "string"
    },
    "osm3s": {
      "description": "Description of Overpass operation (OSM Server Side Scripting)",
      "type": "object",
      "properties": {
        "timestamp_osm_base": {
          "description": "Time when the data was extracted from OSM",
          "type": "string"
        },
        "copyright": {
          "description": "Provides information about the source and licensing of the data",
          "type": "string"
        }
      },
      "required": [
        "timestamp_osm_base",
        "copyright"
      ],
      "additionalProperties": false
    },
    "elements": {
      "description": "List of OSM Elements that compose the object",
      "type": "array",
      "items": {
        "anyOf": [
          {
            "description": "OSM nodes",
            "type": "object",
            "items": {
              "$ref": "#/$defs/osm_nodes"
            }
          },
          {
            "description": "OSM ways",
            "type": "object",
            "items": {
              "$ref": "#/$defs/osm_ways"
            }
          },
          {
            "description": "OSM relations",
            "type": "object",
            "items": {
              "$ref": "#/$defs/osm_relations"
            }
          }
        ]
      }
    }
  },
  "required": [
    "version",
    "generator",
    "osm3s",
    "elements"
  ],
  "additionalProperties": false,
  "$defs": {
    "osm_nodes": {
      "$comment": "##### OSM nodes",
      "description": "Properties of an OSM node",
      "type": "object",
      "properties": {
        "type": {
          "description": "Name of the OSM object type (node)",
          "type": "string"
        },
        "id": {
          "description": "Unique identifier of the OSM node",
          "type": "integer",
          "exclusiveMinimum": 0
        },
        "lat": {
          "description": "Latitude of the node location",
          "type": "number",
          "maximum": 90,
          "minimum": -90
        },
        "lon": {
          "description": "Longitude of the node location",
          "type": "number",
          "maximum": 180,
          "minimum": -180
        },
        "tags": {
          "description": "List of tags for the OSM node",
          "type": "object",
          "patternProperties": {
            "^.*$": {
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      },
      "required": [
        "type",
        "id",
        "lat",
        "lon"
      ],
      "additionalProperties": false
    },
    "osm_ways": {
      "$comment": "##### OSM ways",
      "description": "Properties of an OSM way",
      "type": "object",
      "properties": {
        "type": {
          "description": "Name of the OSM object type (way)",
          "type": "string"
        },
        "id": {
          "description": "Unique identifier of the OSM way",
          "type": "integer",
          "exclusiveMinimum": 0
        },
        "nodes": {
          "description": "List of nodes that delimitate the way",
          "type": "array",
          "properties": {
            "items": {
              "type": "integer"
            }
          }
        },
        "tags": {
          "description": "List of tags for the OSM way",
          "type": "object",
          "patternProperties": {
            "^.*$": {
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      },
      "required": [
        "type",
        "id",
        "nodes"
      ],
      "additionalProperties": false
    },
    "osm_relations": {
      "$comment": "##### OSM relations",
      "description": "Properties of an OSM relation",
      "type": "object",
      "properties": {
        "type": {
          "description": "Name of the OSM object type (relation)",
          "type": "string"
        },
        "id": {
          "description": "Unique identifier of the OSM relation",
          "type": "integer",
          "exclusiveMinimum": 0
        },
        "members": {
          "description": "List of members of an OSM relation",
          "type": "array",
          "items": {
            "description": "Decription of the members that belongs to an OSM relation",
            "type": "object",
            "properties": {
              "type": {
                "description": "Type of object referenced",
                "type": "string"
              },
              "ref": {
                "description": "Reference to the object",
                "type": "integer",
                "exclusiveMinimum": 0
              },
              "role": {
                "description": "Role name of the element in the relation",
                "type": "string"
              }
            },
            "required": [
              "type",
              "ref"
            ],
            "additionalProperties": false
          }
        },
        "tags": {
          "description": "List of tags for the OSM relation",
          "type": "object",
          "patternProperties": {
            "^.*$": {
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      },
      "required": [
        "type",
        "id",
        "members"
      ],
      "additionalProperties": false
    }
  }
}

=== OSMLatam/OSM-Notes-Ingestion/test/command/extra/3335661.json
{
  "version": 0.6,
  "generator": "Overpass API 0.7.62.7 375dc00a",
  "osm3s": {
    "timestamp_osm_base": "2025-07-13T15:04:45Z",
    "copyright": "The data included in this document is from www.openstreetmap.org. The data is made available under ODbL."
  },
  "elements": [

{
  "type": "node",
  "id": 242181605,
  "lat": 22.0000000,
  "lon": 33.4130560
},
{
  "type": "node",
  "id": 242186389,
  "lat": 21.7250000,
  "lon": 33.5529167
},
{
  "type": "node",
  "id": 242206885,
  "lat": 22.0000000,
  "lon": 33.1666667
},
{
  "type": "node",
  "id": 242206891,
  "lat": 22.0000210,
  "lon": 34.0798633
},
{
  "type": "node",
  "id": 2542289902,
  "lat": 21.8705099,
  "lon": 33.7372116,
  "tags": {
    "alt_name": "بيرطويل;بير طويل",
    "alt_name:ar": "بيرطويل;بير طويل",
    "alt_name:en": "Bi'r Tawīl",
    "description": "إقليم لم يطالب به أي بلد.",
    "description:ar": "إقليم لم يطالب به أي بلد.",
    "description:de": "Gebiet, das von keinem Land beansprucht wird",
    "description:en": "Territory unclaimed by any country",
    "description:es": "Territorio no reclamado por ningún país",
    "name": "بئر طويل",
    "name:ar": "بئر طويل",
    "name:de": "Bir Tawil",
    "name:el": "Μπιρ Ταουίλ",
    "name:en": "Bir Tawil",
    "name:es": "Bir Tawil",
    "name:fa": "بئر طویل",
    "name:fr": "Bir Tawil",
    "name:hy": "Բիր-Տավիլ",
    "name:pt": "Bir Tawil",
    "name:ru": "Бир-Тавиль",
    "name:zh": "比尔泰维勒/比爾泰維勒",
    "name:zh-Hans": "比尔泰维勒",
    "name:zh-Hant": "比爾泰維勒",
    "place": "region",
    "wikidata": "Q620634",
    "wikipedia": "ar:بئر طويل"
  }
},
{
  "type": "node",
  "id": 2615199944,
  "lat": 21.7666667,
  "lon": 34.0000000,
  "tags": {
    "alt_name": "بئر حسمة عمر",
    "int_name": "Bîr Hismet ‘Umar, Bir Hismet Umar",
    "name": "بئر حسمة عمر",
    "name:ar": "بئر حسمة عمر",
    "name:ar1": "بئر حسمة عمر",
    "name:de": "Bir Hismet Umar",
    "name:en": "Bir Hismet Umar",
    "name:fr": "Bir Hismet Umar",
    "natural": "spring"
  }
},
{
  "type": "way",
  "id": 22587325,
  "nodes": [
    242206885,
    242186389
  ],
  "tags": {
    "admin_level": "2",
    "border_type": "nation",
    "boundary": "administrative",
    "disputed": "yes",
    "left:country": "بئر طويل",
    "name": "السودان - بئر طويل",
    "name:ar": "السودان - بئر طويل",
    "name:de": "Sudan - Bir Tawil",
    "name:en": "Sudan - Bir Tawil",
    "name:es": "Sudán - Bir Tawil",
    "name:fr": "Soudan - Bir Tawil",
    "right:country": "السودان",
    "source": "CIA World database II",
    "wdb:source": "CIA World database II - africa-bdy.txt - segment 5"
  }
},
{
  "type": "way",
  "id": 255823727,
  "nodes": [
    242181605,
    242206885
  ],
  "tags": {
    "admin_level": "2",
    "attribution": "US Dept. of State Office of the Geographer",
    "border_type": "nation",
    "boundary": "administrative",
    "disputed": "yes",
    "left:country": "بئر طويل",
    "name": "مصر - بئر طويل",
    "name:ar": "مصر - بئر طويل",
    "name:de": "Ägypten - Bir Tawil",
    "name:en": "Egypt - Bir Tawil",
    "name:es": "Egipto - Bir Tawil",
    "name:fr": "Égypte - Bir Tawil",
    "right:country": "مصر",
    "source": "Large Scale International Boundary (US DoS/INR/GGI-06/2013)",
    "source:date": "2013-06"
  }
},
{
  "type": "way",
  "id": 255823728,
  "nodes": [
    242206891,
    242181605
  ],
  "tags": {
    "admin_level": "2",
    "attribution": "US Dept. of State Office of the Geographer",
    "border_type": "nation",
    "boundary": "administrative",
    "disputed": "yes",
    "left:country": "بئر طويل",
    "name": "مصر - بئر طويل",
    "name:ar": "مصر - بئر طويل",
    "name:de": "Ägypten - Bir Tawil",
    "name:en": "Egypt - Bir Tawil",
    "name:es": "Egipto - Bir Tawil",
    "name:fr": "Égypte - Bir Tawil",
    "right:country": "مصر",
    "source": "Large Scale International Boundary (US DoS/INR/GGI-06/2013)",
    "source:date": "2013-06"
  }
},
{
  "type": "way",
  "id": 284530551,
  "nodes": [
    242186389,
    2615199944,
    242206891
  ],
  "tags": {
    "admin_level": "2",
    "border_type": "nation",
    "boundary": "administrative",
    "disputed": "yes",
    "left:country": "بئر طويل",
    "name": "السودان - بئر طويل",
    "name:ar": "السودان - بئر طويل",
    "name:de": "Sudan - Bir Tawil",
    "name:en": "Sudan - Bir Tawil",
    "name:es": "Sudán - Bir Tawil",
    "name:fr": "Soudan - Bir Tawil",
    "right:country": "السودان",
    "source": "CIA World database II",
    "wdb:source": "CIA World database II - africa-bdy.txt - segment 5"
  }
},
{
  "type": "relation",
  "id": 3335661,
  "members": [
    {
      "type": "way",
      "ref": 255823728,
      "role": "outer"
    },
    {
      "type": "way",
      "ref": 255823727,
      "role": "outer"
    },
    {
      "type": "way",
      "ref": 22587325,
      "role": "outer"
    },
    {
      "type": "way",
      "ref": 284530551,
      "role": "outer"
    },
    {
      "type": "node",
      "ref": 2542289902,
      "role": "label"
    }
  ],
  "tags": {
    "alt_name": "بيرطويل;بير طويل",
    "alt_name:ar": "بيرطويل;بير طويل",
    "alt_name:en": "Bi'r Tawīl",
    "boundary": "political",
    "description": "إقليم لم يطالب به أي بلد.",
    "description:ar": "إقليم لم يطالب به أي بلد.",
    "description:de": "Gebiet, das von keinem Land beansprucht wird.",
    "description:en": "Territory unclaimed by any country.",
    "description:es": "Territorio no reclamado por ningún país.",
    "name": "بئر طويل",
    "name:ar": "بئر طويل",
    "name:de": "Bir Tawil",
    "name:el": "Μπιρ Ταουίλ",
    "name:en": "Bir Tawil",
    "name:es": "Bir Tawil",
    "name:fa": "بئر طویل",
    "name:fr": "Bir Tawil",
    "name:hy": "Բիր-Տավիլ",
    "name:pt": "Bir Tawil",
    "name:ru": "Бир-Тавиль",
    "name:uk": "Бір-Тавіль",
    "name:zh": "比尔泰维勒/比爾泰維勒",
    "name:zh-Hans": "比尔泰维勒",
    "name:zh-Hant": "比爾泰維勒",
    "place": "region",
    "timezone": "Africa/Cairo",
    "type": "boundary",
    "wikidata": "Q620634",
    "wikipedia": "ar:بئر طويل"
  }
}

  ]
}
